# docker network create --attachable --subnet 192.168.16.0/24 -d bridge analytics
version: '3.8'

services:
  order-manager-service:
    container_name: order-manager-service
    build:
      context: ./order-manager
    depends_on:
      - order-manager-db
      - kafka
    networks:
      - backend
    environment:
      DB_HOST: order-fulfillment-db
      KAFKA_BROKERS: kafka
  order-fulfillment-service:
    container_name: order-fulfillment-service
    build:
      context: ./fulfillment-service
    depends_on:
      - order-fulfillment-db
      - kafka
    networks:
      - backend
    environment:
      DB_HOST: order-fulfillment-db
      DB_PORT: 3307
      KAFKA_BROKERS: kafka
  order-fulfillment-db:
    container_name: order-fulfillment-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'order-fulfillment-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - target: 3306
        published: 3307
        protocol: tcp
        mode: host
    expose:
      - '3307'
    volumes:
      - order-fulfillment-db:/var/lib/mysql
    networks:
      - backend
  order-manager-db:
    container_name: order-manager-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'order-manager-db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - order-manager-db:/var/lib/mysql
    networks:
      - backend
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - target: 2181
        published: 2181
        protocol: tcp
        mode: host
    networks:
      - backend

  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CREATE_TOPICS: "order-events:1:1"
    volumes:
      - ./:/etc/kafka
    networks:
      - backend

volumes:
  order-manager-db:
  order-fulfillment-db:
networks:
  backend:
    name: backend